// this is the entry point and it is not hashboosted so
// 0. DO NOT CHANGE IT
// 1. RENAME it each time you actually change it
// 2. keep it as small as possible, all initializations should be done in the
// app module, not there
(function (window) {
  'use strict';
  jQuery(document).ready(function () { 
        $("#dialog").dialog({
         autoOpen : false, modal : true, show : "blind", hide : "blind",width:"800px"
       });   
   });  
})(window);
var array=[];
var arrayImg=[];
function openDialogBox(image,label){
    array=[];
    arrayImg=[];
    array.push(label);
    arrayImg.push(image);
   // $('#switchId').is(":checked")
     generateBox(image,label);
     return false;
 }
 
 function getSwitch(image,label){
     var label=array[0];
     var image=arrayImg[0];
     generateBox(image,label);
     //alert($('#switchId').is(":checked"));
 }
 
 function generateBox(image,label){
     $("#imageId").html('<img  style="width:50px;" src="/intent-ai-service/assets/img/'+image +'"></img> <span id="actionLabel">'+label+'</span>'); 
    if(label=="Facebook Messenger"){
      if($('#switchId').is(":checked"))
           $("#contentId").html(' <div class=" description"><p>After you design and test your API.AI agent, you can launch your Messenger both</p><ol><li>Get your Facebook Page Access Token and insert it in the field below.</li><li>Create your own Verify Token (can be any string).</li><li>Click START below.</li><li>Use the Callback URL and Verify Token to create an event in the Facebook Messenger Webhook Setup.</li></ol><p><a href="https://api.ai/docs/integrations/facebook" target="_blank">More in documentation.</a></p></div><div class="row"><label  class="col-sm-3 fieldLabel">Callback URL</label><div  class="col-sm-9"><input  class="inputBox" value="https://bots.api.ai/facebook/ed12f2cd-b784-4011-aafb-4de91453ff63/webhook"  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Verify token</label><div  class="col-sm-9"><input  class="inputBox"   placeholder="Verify token"  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Page access token</label><div  class="col-sm-9"><input  class="inputBox"  placeholder="Page access token"  type="text"/></div></div> <div class="row"><div  class="col-sm-9"></div><div  class="col-sm-3"><button  id="tranningContentSave" type="button" class="md-button" style="margin-left: 51px;" >Start</button></div></div>');
      else
           $("#contentId").html(' <div class=" description"><p>After you design and test your API.AI agent, you can launch your Messenger both</p><ol><li>Get your Facebook Page Access Token and insert it in the field below.</li><li>Create your own Verify Token (can be any string).</li><li>Click START below.</li><li>Use the Callback URL and Verify Token to create an event in the Facebook Messenger Webhook Setup.</li></ol><p><a href="https://api.ai/docs/integrations/facebook" target="_blank">More in documentation.</a></p></div><div class="row"><label  class="col-sm-3 fieldLabel">Callback URL</label><div  class="col-sm-9"><input  class="inputBox" value="https://bots.api.ai/facebook/ed12f2cd-b784-4011-aafb-4de91453ff63/webhook" readonly="true"  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Verify token</label><div  class="col-sm-9"><input  class="inputBox" readonly="true"  placeholder="Verify token" type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Page access token</label><div  class="col-sm-9"><input readonly="true"  class="inputBox" placeholder="Page access token"  type="text"/></div></div> <div class="row"><div  class="col-sm-9"></div><div  class="col-sm-3"><button  id="tranningContentSave" type="button" class="md-button" style="margin-left: 51px;" >Start</button></div></div>');
    }
       
    else if (label=="Actions on Google")
        $("#contentId").html(' <div class=" description"><p style="margin-top:15px;"><a href="https://developers.google.com/actions/" target="_blank">Learn more</a> about Actions on Google <br><a href="https://developers.google.com/actions/" target="_blank">Learn more</a> about integration with Actions on Google <br><a href="https://developers.google.com/actions/" target="_blank">Learn more</a> about Actions on Google configuration limits <br>Test integration in <a href="https://developers.google.com/actions/" target="_blank">Web Simulator</a></p><div class="row" style="margin-top:15px;"><div class="col-sm-12"><input type="text" placeholder="Invocation name for testing* ." style="border-width: 0 0 1px;width: 100%;"></div></div><div style="margin-bottom:15px;color: grey;">Uniques name used to refer your action while testing</div> <div style="margin-top:15px;color: grey;">Google project id</div><div class="row"  style="margin-bottom:15px;  ;color:black;"><div class="col-sm-12"><input type="text" placeholder="traffic-e3dc9 " style="border-width:0 0 1px;width:100%;"></div></div> <div >Project name from <a href="https://console.developers.google.com/apis/api/actions.googleapis.com/overview?project=traffic-e3dc9"target="_blank">Google Developer Console</a></div><p>TTS voice*: male1<br>Welcome Intent* <div class="googleDialogInputBox">Welcome1</div></p><br><div><input style="margin: 0 0 0; width: 3%;" type="checkbox" name="">Sign in required for welcome intent</div><div style="margin-top: 10px;">Additional triggering intents</div> <div style="margin-top: 10px;" class="googleDialogInputBox">Select intents</div><div class="decription" style="margin-top:15px;margin-bottom:10px;"><a >Define oAuth Linking</a></div></div>');
     else if (label=="Skype")
        $("#contentId").html(' <div class=" description"><p>Build a conversational bot for Skype.</p><p>When your API.AI agent is ready, follow these instructions to integrate it with your Skype bot:</p><ol><li>Create a new bot in the Microsoft Bot Framework.</li><li>Create your own Verify Token (can be any string).</li><li>Fill in the Name, Bot handle, and Description fields in the Bot profile section.</li><li>Copy the Request URL below and insert it to the ‘Messaging endpoint’ field in the Configuration section in the Skype bot settings.</li><li>In the same section, click ‘Create Microsoft App ID and password’ button.</li><li>Copy the generated password and the App ID from your Skype bot settings to the respective fields below.</li><li>Complete the Skype bot registration by filling in the Publisher profile section and clicking Register.</li><li>Click ‘START’.</li></ol><p><a href="https://api.ai/docs/integrations/facebook" target="_blank">More in documentation.</a></p></div><div class="row"><label  class="col-sm-3 fieldLabel">Microsoft App ID</label><div  class="col-sm-9"><input  class="inputBox" placeholder="Application id" readonly="true"  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Microsoft App Password</label><div  class="col-sm-9"><input  class="inputBox"   placeholder="Select id" type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Request URL</label><div  class="col-sm-9"><input  class="inputBox" value="https://bots.api.ai/skype/768adc35-d6c2-49c1-bac8-1c5a64f04b24/webhook" readonly="true"  type="text"/></div></div> <div class="row"><div  class="col-sm-9"></div><div  class="col-sm-3"><button  id="tranningContentSave" type="button" class="md-button" style="margin-left: 51px;" >Start</button></div></div>');
     else if (label=="Twitter")
        $("#contentId").html(' <div class=" description"><p>Train your Twitter bots to understand natural language.</p><p>When your API.AI agent is ready, follow these instructions to connect it to Twitter:</p><ol><li>In Twitter Application Management, click ‘Create new App’ and fill in all the fields.</li><li>In the "Permissions" tab, select "Read, Write and Access direct messages" in the "Access" area and click "Update Settings".</li><li>In the Key and Access Tokens  tab, click the "Create my access token" button.</li><li>Enter the Bot Username in the respective field below.</li><li>From the "Key and Access Tokens" tab, copy Consumer Key, Consumer Secret, Access Token, and Access Token Secret and paste in the respective fields below.</li><li>Click ‘START’.</li></ol><p><a href="https://api.ai/docs/integrations/facebook" target="_blank">More in documentation.</a></p></div><div class="row"><label  class="col-sm-3 fieldLabel">Bot Username</label><div  class="col-sm-9"><input  class="inputBox" placeholder="" readonly="true"  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Consumer Key</label><div  class="col-sm-9"><input  class="inputBox"   placeholder="" type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Consumer Secret</label><div  class="col-sm-9"><input  class="inputBox"  readonly=""  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Access Token</label><div  class="col-sm-9"><input  class="inputBox"  readonly=""  type="text"/></div></div><div class="row"><label  class="col-sm-3 fieldLabel">Access Token Secret</label><div  class="col-sm-9"><input  class="inputBox"  readonly=""  type="text"/></div></div> <div class="row"><div  class="col-sm-9"></div><div  class="col-sm-3"><button  id="tranningContentSave" type="button" class="md-button" style="margin-left: 51px;" >Start</button></div></div>');
     else if (label=="Web Demo")
        $("#contentId").html(' <div class=" description"><p style="margin-top:15px;">Test the agent on its own page. Share the link to the page or embed the ` widget in other websites to get more conversations going. More in documentation.</p><p><a ssyle="margin-top:15px;" href="https://bot.api.ai/768adc35-d6c2-49c1-bac8-1c5a64f04b24" target="_blank" >https://bot.api.ai/768adc35-d6c2-49c1-bac8-1c5a64f04b24 <span class="glyphicon glyphicon-pencil"></span></a></p> <div class="row" style="height:15px;background:  #f8f8f8; margin-top:15px;"><div  class="col-sm-1 glyphicon glyphicon-exclamation-sign"></div><div style="font-size:12px; "  class="col-sm-10">Seems that your agent info is not filled yet. Set icon and description for better end-user experience.</div> <div  class="col-sm-1 glyphicon glyphicon-cog"></div></div></div>');
     else 
        $("#contentId").html(' <div class=" description"><p style="margin-top:15px;">Test the agent on its own page. Share the link to the page or embed the ` widget in other websites to get more conversations going. More in documentation.</p><p><a ssyle="margin-top:15px;" href="https://bot.api.ai/768adc35-d6c2-49c1-bac8-1c5a64f04b24" target="_blank" >https://bot.api.ai/768adc35-d6c2-49c1-bac8-1c5a64f04b24 <span class="glyphicon glyphicon-pencil"></span></a></p> <div class="row" style="height:15px;background:  #f8f8f8; margin-top:15px;"><div  class="col-sm-1 glyphicon glyphicon-exclamation-sign"></div><div style="font-size:12px; "  class="col-sm-10">Seems that your agent info is not filled yet. Set icon and description for better end-user experience.</div> <div  class="col-sm-1 glyphicon glyphicon-cog"></div></div></div>');    
    $("#dialog").dialog("open");
 }